### ISSUE TITLE
reconciliation loop fails with GitHub authentication, jenkins-operator connot authenticate

### ISSUE THREAD

**Issue by adaniline-traderev** [jenkinsci/kubernetes-operator#11]
Security document states that other realms are possible to configure through scripts. This breaks the reconciliation-operator loop, however, since jenkins-operator cannot authenticate Jenkins API calls

**Comment by tomaszsek** [comment]
https://github.com/jenkinsci/kubernetes-operator/blob/master/docs/security.md#jenkins-access-control
`Any change to Security Realm or Authorization requires that user called jenkins-operator must have admin rights because jenkins-operator calls Jenkins API.`

You have to install Matrix-based security plugin and add entry for user `jenkins-operator` to be admin.

**Comment by adaniline-traderev** [comment]
Thanks, I missed that. 

In our case, it means that jenkins-operator must somehow login to github, and then go through OAuth2 flow. 

I think there is an issue in Jenkins to support multiple security realms - this would help with that
