### ISSUE TITLE
Query: Upstream Developer Calls on the Jenkins Operator

### ISSUE THREAD

**Issue by waveywaves** [jenkinsci/kubernetes-operator#186]
Are there any upstream developer calls which happen discussing the Operator and the path the Operator is taking. I am much interested in attending them if possible, and it would also help improving contributions to the operator.

**Comment by jakalkhalili** [comment]
Hi @waveywaves 

@tomaszsek is the main creator of Jenkins Operator. Also @pawekprazak makes decisions about operator. If you have any ideas or feature requests - please create issue. If you are interested in contributing please make a PR.

Cheers

**Comment by pawelprazak** [comment]
Hi @waveywaves, thank you for your interest in the jenkins operator and its future.

The lead developer is @tomaszsek and I help out from time to time, also @jakalkhalili is working full time on the operator ATM.

There was no need for a video call so far, since no one expressed interest in it, but now it's worth considering.
If you are by any chance at Jenkins World in Lisbon, Tomek will have a presentation there so this would be a great opportunity to meet in person: https://devopsworldjenkinsworld2019lisbo.sched.com/speaker/tomasz.sek.88

**Comment by waveywaves** [comment]
@jakalkhalili Surely :) Thanks for that.
@pawelprazak Thanks for the updates on the talk.

**Comment by pawelprazak** [comment]
let's see if the new slack channel is enough, if not, we'll schedule a call through slack

closing
