### ISSUE TITLE
Understand how this works as an example

### ISSUE THREAD

**Issue by nilave** [jenkinsci/kubernetes-operator#464]
Thanks for this great operator. I have deployed this in my AKS cluster and would like to understand how this works as a practical scenario. Like if I add a new set to base plugins to my CR will it redeploy all the pods with the new set of plugins. Also while redeploying whether there will be any loss of data

**Comment by antoniaklja** [comment]
Hi @nilave, please find answers for your questions below:

> I have deployed this in my AKS cluster and would like to understand how this works as a practical scenario.
Well, it's highly recommended to familiarize yourself with Kubernetes operator pattern. Long story short - the operator uses various APIs (groovy scripts, configuration files, external plugins) to initially configure and reconcile Jenkins instance. 

> Like if I add a new set to base plugins to my CR will it redeploy all the pods with the new set of plugins.
It depends on the Jenkins lifecycle, rather than operator part. For example, when you install a plugin, the Jenkins doesn't need to be restarted, however, if you want to configure specific plugin - then the Jenkins restart is required to apply a new configuration. 

> Also while redeploying whether there will be any loss of data
No, the Jenkins state is persistent using built-in Kubernetes Persistent Volume Claim (PVC). As long as the desired configuration is already defined in Kubernetes Custom Resource, everything should be there after the restart. When you changed something manually it won't be persisted after the restart.

Does it answer your question? Is there anything you'd like to know more or do you see some obvious gaps in the documentation?

**Comment by Sig00rd** [comment]
Closing this since the questions have been thoroughly answered. If you have any more questions, feel free to file another issue!
