### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by Harguer** [jenkinsci/kubernetes-operator#521]
**Describe the solution you'd like**
Wondering if could be added arm64 arch support.

**Describe alternatives you've considered**
I have tried with standard arm64 image, but did not work since it does not incorporate operator features

**Additional context**
No additional context

**Comment by Harguer** [comment]
Still wonder if it would have support for arm64 someday

**Comment by Sig00rd** [comment]
We're not currently planning on explicitly supporting arm64 for now, but you should be able to build Operator runtime image yourself. In Dockerfile, change `GOARCH` to `arm64` in the build command (line 24) and use `gcr.io/distroless/static:nonroot-arm64` as base image for the operator (line 28).

**Comment by Harguer** [comment]
hey @Sig00rd. That is awesome, thanks for the reply and for the directions, I'm all set with this temporary workaround, seems working pretty well for my test.

**Comment by Sig00rd** [comment]
That's great to hear @Harguer . I'm closing this issue since the instructions seemed to help (though please ping me here/on project's Slack if I'm wrong - I could only verify that the image builds, I've got nothing to run it on) and support for arm64 is not really on the roadmap right now. But if you experience with this setup feel free to file up a separate issue with up to date information.
Thank you for your input!
