### ISSUE TITLE
[Question/Bug]. Delay Jenkins start when the restore.sh is running

### ISSUE THREAD

**Issue by sknight80** [jenkinsci/kubernetes-operator#679]
**Describe the bug**
It is not a bug, I think, but I would like to know, if there is a way to delay Jenkins startup until the `restore.sh` (or the restore) process is done.  If we could, then we can avoid unnecessary GitHub repo reindexing.

**To Reproduce**
1) You should have lots of logs with lots of jobs (jobs number: 20+, build number: 10+ per jobs, log size 1G+)
2) Backup your logs then 
3) Restart the `jenkins` pod
4) Wait until the `jenkins-operator` re-initialize your `jenkins` pod
5) Check the logs:
  a) Jenkins is up and running after the plugins are installed and all the custom configuration and running seeder job
  b) The backend still running the `restore.sh` command while the seeder job recreates your jobs

**Additional information**
Our multipipeline job when it is created the Jenkins do the initial scanning because we don't have the logs from the previous system run (yet) so it will run an initial build on each of your branches on that given repository

Kubernetes version: 1.18
Jenkins Operator version: `0.5.0`

Add error logs about the problem here (operator logs and Kubernetes events).
N/A

**Comment by sknight80** [comment]
Hm maybe it does. The problem is the asynchronous run. Like the restore process still running (unzip tar into Jenkins file system, about 2.2G of tar.gz file) when the Jenkins seeder job starts. Which means we don't have the latest (restored) status of the job because of unzip.  Does this make sense?

**Comment by thecooldrop** [comment]
Yes, but that does not matter to the seed job really. You just want to prevent the pipeline from running after being indexed? I do understand what you are describing, but what is the desired behavior?

The first option would be: Jenkins is not available until the restore.sh is done

Second option would be: Jenkins becomes available before the restore.sh is done, but the pipelines are not executed on first indexing

Third option would be, and I do not know if and how this would work: The restore.sh is ran before the Jenkins process is started, so that the file system is fully initialized before Jenkins process even starts. This may be achievable via an initContainer, but input from maintainers would be necessary.

**Comment by sknight80** [comment]
I prefer the first option.  Like, don't start the Jenkins until all the jobs result and artifact haven't been restored yet.  Once the restore process is done, start up the Jenkins and start the seeder job.  With this sequence, we could easily avoid unnecessary GitHub indexing event + job building.  (Because when Jenkins saw a job first time, will kick out an initial build, and if you have 100+ jobs and each repo has just five open branches, that mean you have 500+ jobs in the queue on start-up time)

**Comment by thecooldrop** [comment]
You can actually turn of the job triggering on branch indexing. This means that despite the jobs getting indexed, nothing will run. This is provided by branch source plugin.

**Comment by sknight80** [comment]
@thecooldrop, that is true. The problem is that you have to turn it off after the restart, and everything is done on each job because when you have a new branch in a repo, the related job will not trigger.   I got it; we don't want to change the current workflow; I want to bring an issue to the community to solve it and to see if others have this problem or not.

**Comment by pniederlag** [comment]
We currently have put the seed job to an invalid pattern. This way jenkins starts regularly... restore is running... seed job won't actually create any jobs... whenever we run into this we wait until restore is done und then edit the seed job from "intentional-invalid.jenkins" to "*.jenkins"... Not great, but better than "build-bombs" probably even jamming the cluster, ending up in endless kill/restart loops...

**Comment by brokenpip3** [comment]
@pniederlag https://github.com/jenkinsci/kubernetes-operator/issues/843#issuecomment-1575568828
