### ISSUE TITLE
Is there a way to configure multiple Jenkins-masters to enable High Availability

### ISSUE THREAD

**Issue by nithinvithayathil** [jenkinsci/kubernetes-operator#730]
Is there a way to achieve High availability for Jenkins master by creating multiple Replicas for Jenkins Master?

Currently due to high usage my Jenkins master Pod's memory usage increases and the kubernetes Node restarts my Jenkins-master almost every day. Since i have only 1 Jenkins master pod running, there is a downtime for Jenkins almost everyday. I think i can stop this from happening if i have multiple Jenkins-master node running in multiple nodes.

Is there a way i can achieve this? If so can anyone please help me on how i can do that?

**Comment by thecooldrop** [comment]
While I do understand what you would like to achieve I think that the issue lies somewhere else. I am using the Operator at my job and we are experiencing a similar issue, but the Jenkins master node runs out of memory every couple of days. It seems to be a known issue, due to memory leaks in Jenkins so I would ask you to analyze again, and check if memory usage of Jenkins master Pod is increasing over time, which if yes then it could indicate a memory leak.


Memory leaks can be caused by installed plugins and are hard to diagnose.

My proposal would be to do following steps:

- Increase the available memory given to Jenkins master Pod
- Configure a CronJob which restarts the Jenkins master Pod at time when nobody needs the Jenkins

This way you will be able to increase the amount of time between OOM errors, and you will not be getting the errors during the day, when you need the Jenkins. I know that this solution is temporary, but should enable you to take the focus of the issue and to diagnose the actual underlying memory problem without pressure.

**Comment by nithinvithayathil** [comment]
Closing this issue

**Comment by nithinvithayathil** [comment]
> While I do understand what you would like to achieve I think that the issue lies somewhere else. I am using the Operator at my job and we are experiencing a similar issue, but the Jenkins master node runs out of memory every couple of days. It seems to be a known issue, due to memory leaks in Jenkins so I would ask you to analyze again, and check if memory usage of Jenkins master Pod is increasing over time, which if yes then it could indicate a memory leak.
> 
> Memory leaks can be caused by installed plugins and are hard to diagnose.
> 
> My proposal would be to do following steps:
> 
> * Increase the available memory given to Jenkins master Pod
> * Configure a CronJob which restarts the Jenkins master Pod at time when nobody needs the Jenkins
> 
> This way you will be able to increase the amount of time between OOM errors, and you will not be getting the errors during the day, when you need the Jenkins. I know that this solution is temporary, but should enable you to take the focus of the issue and to diagnose the actual underlying memory problem without pressure.

The current memory that i have allocated for jenkins master container is 10GB, and 2 GB for backup container. But while some pipeline like regression testing runs, the master container will shoot up and will eventually gets restarted

**Comment by papi83dm** [comment]
@nithinvithayathil  did you find a solution for this? i'm experiencing the same issue.

**Comment by talk2aanand** [comment]
Any update on this, this is very urgent and impact my producation workload.

**Comment by grafenam** [comment]
we experience the same issue. Any solution to enable multiple replicas for Jenkins master?

**Comment by pniederlag** [comment]
Is HA really something the operator can solve given that HA is kind of missing feature in jenkins itself?

https://welltempereddeveloper.com/ci/cd/2019/04/08/jenkins-ha-multiple-masters.html

From my perspective: You can safely use the operator to run multiple jenkins masters with multiple (kubernetes-based) slaves from a single code-base. True HA is just not solvable within the scope of this project. Running multiple replicas  with one Jenkins-CRD seems not a good design decision to me.

**Comment by brokenpip3** [comment]
I totally agree with @pniederlag the upstream jenkins community lack of a HA solution (only with cloudbees version that require a subscription) so it will be hard to implement something at the operator level.
If something will comes up in the future I'm happy to take a look and try to implement it here as well :)
