### ISSUE TITLE
seed-job-agent provisioning broken since Jenkins 2.348

### ISSUE THREAD

**Issue by steigr** [jenkinsci/kubernetes-operator#742]
**Describe the bug**
Since 2.348 the operator fails to parse the slave-agent.jnlp xml document.

**To Reproduce**
Create a operated jenkins in version 2.348.

**Additional information**

Kubernetes version: v1.23.6+k3s1
Jenkins Operator version: 0.7.0

Add error logs about the problem here (operator logs and Kubernetes events).

The Operator finishes to inject CasC instructions. Then it fails to parse the JNLP body:

```
jenkins-operator-7f956b89bc-5xcpj jenkins-operator 2022-05-17T15:48:24.279Z	WARN	controller-jenkins	Reconcile loop failed 10 times with the same errors, giving up: Node secret cannot be parsed
jenkins-operator-7f956b89bc-5xcpj jenkins-operator github.com/jenkinsci/kubernetes-operator/pkg/client.(*jenkins).GetNodeSecret
jenkins-operator-7f956b89bc-5xcpj jenkins-operator 	/workspace/pkg/client/jenkins.go:209
jenkins-operator-7f956b89bc-5xcpj jenkins-operator github.com/jenkinsci/kubernetes-operator/pkg/configuration/user/seedjobs.(*seedJobs).createAgent
```

The JNLP format looks like the following:
```xml
<jnlp>
	<application-desc>
		<argument>0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef</argument>
		<argument>seed-job-agent</argument>
		<argument>-workDir</argument>
		<argument>/home/jenkins</argument>
		<argument>-internalDir</argument>
		<argument>remoting</argument>
		<argument>-url</argument>
		<argument>https://jenkins.example.com/</argument>
	</application-desc>
</jnlp>
```

before the structure was more like this:

```xml
<jnlp codebase="https://jenkins.example.com/computer/seed-job-agent/" spec="1.0+">
<information>
	<title>Agent for seed-job-agent</title>
	<vendor>Jenkins project</vendor>
	<homepage href="https://jenkins-ci.org/"></homepage>
</information>
<security>
	<all-permissions></all-permissions>
</security>
<resources>
	<j2se version="1.8+"></j2se>
	<jar href="https://jenkins.example.com/jnlpJars/remoting.jar"></jar>
</resources>
<application-desc main-class="hudson.remoting.jnlp.Main">
	<argument>0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef</argument>
	<argument>seed-job-agent</argument>
	<argument>-workDir</argument>
	<argument>/home/jenkins</argument>
	<argument>-internalDir</argument>
	<argument>remoting</argument>
	<argument>-url</argument>
	<argument>https://jenkins.example.com/</argument>
</application-desc>
</jnlp>
```

(XML has been re-formatted for readability. it's all in one line).

**Comment by Pikabanga** [comment]
We are having the same problem after upgrading from docker image `jenkins:2.343-jdk11` to `jenkins:2.348-jdk11`

**Comment by rkrzewski** [comment]
I'm seeing this too. Downgrading Jenkins to 2.347 fixes the problem - for now.

**Comment by kodil** [comment]
any news regarding this issue ?

**Comment by sli720** [comment]
What's the status on that issue? I'm getting the same error when I want to update to the latest LTS version and have to stay on the older version for now.

**Comment by sli720** [comment]
Is it somehow possible to workaround this bug?

**Comment by cbernard-psee** [comment]
Hi, sharing the pain here, this issue prevents us to use the latest LTS release ... Any update to share on a fix or workaround will be more than welcome :-)

**Comment by sli720** [comment]
Is this project still active or looking for maintainers?

**Comment by toabi** [comment]
Same error here, tried to upgrade because some indirect dependency plugins really start breaking with current other ones. :(

**Comment by pniederlag** [comment]
regex in jenkins seems to be relevant (?)
https://github.com/jenkinsci/kubernetes-operator/blob/3a143a08316f4935414b3f935f2c2b44def311a1/pkg/client/jenkins.go#L16

**Comment by pniederlag** [comment]
docker pull carintech/jenkins:operator-81f4742b10 is a docker-image where this problem is fixed and which is capable to run with current lts image from jenkins.

Requirements:

* Update the [CRD from master](https://github.com/jenkinsci/kubernetes-operator/blob/master/chart/jenkins-operator/crds/jenkins-crd.yaml) so you can also set  seedJobAgentImage
* in deployment of operator set image to carintech/jenkins:operator-81f4742b10
* in CR for jenkins set seedJobAgentImage: jenkins/inbound-agent:3071.v7e9b_0dc08466-1
* use jenkins/jenkins:2.361-3-lts

**Comment by brokenpip3** [comment]
@pniederlag why not a PR vs upstream here?

**Comment by rkrzewski** [comment]
@brokenpip3 PR would be good, but this project appears to be dead. No one around to merge the PR and cut a release...

**Comment by brokenpip3** [comment]
I asked today in virtuslab slack about the status of this project.
In case they do not have the time to maintain the project I think that with just a couple of new maintainers this project could be revitalized, if you see the last major issues were fixed by the community PRs directly.

Let's see what they reply

**Comment by brokenpip3** [comment]
nope, let's try to ping @Sig00rd here

**Comment by brokenpip3** [comment]
@pniederlag any chance to create the PR? otherwise I can do it, so at least since we are trying to get attention they can just merge the community PR

**Comment by rkrzewski** [comment]
@brokenpip3 if you feel motivated to push this through, you could create your own fork, cherry-pick @pniederlag's commit and post the PR yourself.
But since the maintainers appear to be AWOL, maybe we should try to get Jenkins maintainers involved somehow? Kubernetes is a de-facto industry standard these days and this project provides a crucial integration piece. I believe it has it's role in long term viability of Jenkins as a whole.

**Comment by brokenpip3** [comment]
>maybe we should try to get Jenkins maintainers involved somehow? Kubernetes is a de-facto industry standard these days and this project provides a crucial integration piece. I believe it has it's role in long term viability of Jenkins as a whole.

I totally agree with this ^, we should open a separate issue and use that to gain attention from the current maintainers and the jenkinsci ones.

My request of PR was only to have the right PR to be reviewed and merged

**Comment by brokenpip3** [comment]
Everybody: I finally create the PR to fix this issue (based on @pniederlag work) and all the others issues: https://github.com/jenkinsci/kubernetes-operator/pull/784

Please take a look and test and let me know.
