### ISSUE TITLE
Use ephemeral PVC for JENKINS_HOME

### ISSUE THREAD

**Issue by tomvopat** [jenkinsci/kubernetes-operator#769]
**Describe the solution you'd like**
For big projects with many jobs and many archived logs, it can happen that JENKINKS_HOME directory takes all the node's disk capacity as it is of type `emptyDir`. Using an [ephemeral PVC][1] for JENKINS_HOME would solve this issue.

[1]: https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/#generic-ephemeral-volumes

**Comment by brokenpip3** [comment]
Yep agree this is something we should implement to avoid evicted pods and not ready nodes due to disk pressure.

**Comment by sonali-rajput** [comment]
Do I need to make the changes in the default configuration or make a new one separately?

**Comment by tomvopat** [comment]
Can you elaborate a bit? I'm not sure what you mean...

**Comment by dashashutosh24** [comment]
@brokenpip3 Is this being worked on? Having a PVC for jenkins home directory would really be useful.

**Comment by brokenpip3** [comment]
Hi @dashashutosh24 this is not a pvc for the home directory, it's just using ephemeral pvc instead of emptydir as home directory (https://github.com/jenkinsci/kubernetes-operator/issues/779#issuecomment-1449081454).
If you want to have a persistent volume for the whole home directory you can use the official jenkins helm chart :)
Maybe in the future we may add asmall portion of the home directory like `secrets` but it's not planned yet.
Coming back to the original request: I want to work on this soon :)

**Comment by dashashutosh24** [comment]
@brokenpip3 Thanks for the response. Just a quick question, I tried mounting a PV at /var/lib/jenkins/secrets to preserve the secrets to allow agent reconnection after master comes back up once its down. But still the agent wasn't able to connect to the master. This is in relation to #691 . Any idea how to tackle this?

**Comment by brokenpip3** [comment]
Let's move the conversation in that issue
